1.项目基本配置     创建SpringBoot工程，导入web、velocity和aop等jar包     在pom.xml包含各种依赖，使得程序可以启动起来     创建本地Git仓库，并提交
2.基本框架的开发
    创建基本的controller，service和model层。
    controller中使用注解配置，requestmapping，responsebody基本可以解决请求转发以及响应内容的渲染。responsebody自动选择viewresolver进行解析。
    使用pathvariable和requestparam传递参数。
    使用velocity编写页面模板，注意其中的语法使用。常用$!{}和${}
    使用http规范下的httpservletreques和httpservletresponse来封装请求和相响应，使用封装好的session和cookie对象。
    使用重定向的redirectview和统一异常处理器exceptionhandler

3.数据库配置和首页的创建
    使用mysql创建数据库和表。
    加入mybatis和mysql的maven仓库，由于现在版本的springboot不再支持velocity进而导致使用较早版本的springboot 1.4.0。
    接下来写controller，dao和service。注意mybatis的注解语法以及xml的配置要求:xml要求放在resource中并且与dao接口在相同的包路径下。
    application.properties增加spring配置数据库链接地址。

    两个小工具：
        ViewObject:方便传递任何数据到Velocity
        DateTool:velocity自带工具类

    写好静态文件html css和js。并且注意需要配置
    spring.velocity.suffix=.html 保证跳转请求转发到html上
    spring.velocity.toolbox-config-location=toolbox.xml

    熟悉home.html的内容

4.以上3步中，遇到的头疼的BUG
  （1）Test单元测试没有运行的图标
	ToutiaoinformationApplicationTests测试类必须是public，不能省略不写，否则Test单元测试没有运行的绿三角图标
  （2）空指针异常
java.lang.NullPointerException: null
at org.springframework.boot.web.servlet.view.velocity.EmbeddedVelocityToolboxView.setContextToolbox(EmbeddedVelocityToolboxView.java:65) ~[spring-boot-1.3.8.RELEASE.jar:1.3.8.RELEASE]...............
	原因：
在配置文件application.properties:
spring.velocity.suffix=.html
spring.datasource.url=jdbc:mysql://localhost:3306/wenda?useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234
mybatis.config-location=classpath:mybatis-config.xml
spring.velocity.toolbox-config-location=toolbox.xml

引入了最后一个文件，但是，在项目中忘记添加了，因为暂时还不需要这个功能，所以，由于项目中缺失这个配置文件，它找不到，因此，报空指针异常。

        参见博客：https://www.cnblogs.com/lchzls/p/6677687.html

  （3）Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	参见博客https://blog.csdn.net/sihai12345/article/details/80744012
	需要导入依赖
	<dependency>
     <groupId>javax.xml.bind</groupId>
     <artifactId>jaxb-api</artifactId>
     <version>2.3.0</version>
 </dependency>
 <dependency>
     <groupId>com.sun.xml.bind</groupId>
     <artifactId>jaxb-impl</artifactId>
     <version>2.3.0</version>
 </dependency>
 <dependency>
     <groupId>com.sun.xml.bind</groupId>
     <artifactId>jaxb-core</artifactId>
     <version>2.3.0</version>
 </dependency>
 <dependency>
     <groupId>javax.activation</groupId>
     <artifactId>activation</artifactId>
     <version>1.1.1</version>
 </dependency>

  （4）最头疼的是现在spring已经不支持velocity了，在集成velocity的时候，出现了很多错误，就是版本和依赖的问题，具体参见项目的pom.xml内容
	参考博客：https://www.jianshu.com/p/85a7caabbbfa
	还在环境里手动加了一个jar包（自己下载的）：velocity-engine-core-2.0.jar
	（按Ctril+Shift+Alt+S -> Modules->Dependency-> + -> 手动加入jar包）
  （5）还有其他的一些bug，都是小bug了，一下子能解决的那种