#新增评论和站内信功能#
以后需要新增的业务功能：
	分页
	评论的敏感词过滤
	发送站内信

首先建立表comment和message分别代表评论和站内信。

依次开发model，dao，service和controller。

评论的逻辑是每一条资讯下面都有评论，显示评论数量，具体内容，评论人等信息。

消息的逻辑是，两个用户之间发送一条消息（这里的发送消息是通过postman来得到的数据），有一个唯一的会话id，这个会话里可以有多条这两个用户的交互信息。
通过一个用户id获取该用户的会话列表，再根据会话id再获取具体的会话内的多条消息。

逻辑清楚之后，再加上一些附加功能，比如显示未读消息数量，根据时间顺序排列会话和消息。

本节内容基本就是业务逻辑的开发，没有新增什么技术点，主要是前后端交互的逻辑比较复杂，前端的开发量也比较大。

记录一下这里最复杂的sql语句：
select m.* ,t.cnt
from message m ,(select MAX(id) as id, COUNT(conversation_id) as cnt from message where from_id=17 or to_id=17 group by conversation_id) t
where m.id = t.id
order by created_date desc;

遇到的BUG

资讯详情页detail.html中的$date.format('yyyy-MM-dd HH:mm:ss', $!{commentvo.comment.createdDate})时间显示不出来，
找了很久的原因，原来是因为Comment实体类中，getter和setter的方法名字有误，本来应该是setCreatedDate，可我写成了setCreateDate
教训：一定要仔细，如果页面上遇到错误了，找错误的路线：先从前端找，在找Controller，接着找Service，再找DAO，最后找相应的实体类

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
问题原因：mysql服务断开了
解决办法：需要用管理员的权限打开，将目录调整到mysql的安装目录下的bin目录下，以管理员权限打开cmd，输入命令net start mysql，即可成功

在postman中给http://127.0.0.1:8080/msg/addMessage发送参数时，我选择的是Body页签导致错误，应该选择Params页签
此外，发送时报Could not get any response错误，解决办法参考博客https://blog.csdn.net/Mr_Runner/article/details/88313847
我的错误是通过第四种方法解决的，也就是在postman中的settings里关闭Global Proxy Configuration

[SQL]select * from message group by conversation_id
-- select @@global.sql_mode

[Err] 1055 - Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'toutiao.message.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

打开navcat，

用sql查询：

select @@global.sql_mode

查询出来的值为：

ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

去掉ONLY_FULL_GROUP_BY，重新设置值。

set @@global.sql_mode
='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

重新打开navcat执行语句就好了

group by分组后获得每组中时间最大的那条记录（花了我一晚上的时间解决这个bug）
版本：mysql-5.7.27-winx64
select *,count(id) as cnt
from (select * from message where from_id=17 or to_id=17 order by id,created_date DESC ) o
group concat conversation_id;
并不能实现功能，这是个bug，网友解释的原因是：因为group by聚合后的结果在select中只能是聚合的值

我实践出来的原因是：不管子表o是升序还是降序，group by均只能选择出每组内的第一条最小时间的那个记录，因为group by控制不了选择最大的记录还是最小的记录，可以通过max或者min辅助来做选择，也就是只能控制聚合出来的值，也就是网友说的group by聚合后的结果只能显示在select中的聚合的值！
下面的语句就可以解决：通过聚合，先选择出每组内最大的id（每组内最大的id代表了最新的时间），然后通过带有in谓词的子查询，就可以查询出每组中时间最大的那条记录！！！
select * from message where id in(select MAX(id) as id from message group by conversation_id);